# Generated by Django 4.2.3 on 2024-01-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="DailyWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("min_temp", models.FloatField()),
                ("max_temp", models.FloatField()),
                (
                    "brief_description",
                    models.CharField(
                        choices=[
                            ("Ensolarado", "Ensolarado"),
                            ("Nublado", "Nublado"),
                            ("Chuvoso", "Chuvoso"),
                            ("Parcialmente nublado", "Parcialmente nublado"),
                            ("Neve", "Neve"),
                            ("Granizo", "Granizo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_weather",
                        to="weather.city",
                        unique_for_date="date",
                    ),
                ),
            ],
        ),
    ]
